#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinJoin Configuration File:
#  You can use & for color coding in your messages
#  You can use {player} to get the player's name
#  You can use {line} to make the message go to a new line. (NOTE: does not work with title + subtitle options)
#   Default Config:
#      title: "&aWelcome To The Server This Can Be Editied In Config.yml"
#      subtitle: "&bThis Is A Great Server!"
#      no-permission: "&cYou Do Not Have Permission To Use This Command"
#      guardian-curse: "enabled"
#      message: "&aWelcome To The Server {player}"

# The below config is the message on top that sends when a player joins the server (title)
title: "&bWelcome To The Server"

# The below config is the message on the bottom that sends when a player joins the server (subtitle)
subtitle: "&bThis Is A Great Server"

# The below config is the message that sends when a player does not have permission to use the titlejoin command (no permission)
no-permission: "&bYou Do Not Have Permission To Use This Command"

# The below config enabled or disables the elder guardian curse when you join the server (Options: enabled or disabled)
guardian-curse: "&benabled"

# The below config allows you to send a message to the player when they join
message: "&bWelcome To The Server {player}"
...
